### ISSUE TITLE
example1-mapping-csv.ttl formatted as HTML instead of Turtle, causing jena riot parsing error:"Bad character in IRI" 

### ISSUE THREAD

**Issue by dbooth-boston** [oeg-upm/morph-rdb#31]
Following instructions at https://github.com/oeg-upm/morph-rdb/wiki/Installation-using-Git-and-Maven for testing with CSV examples, a parsing error causes a stack trace:
```
$ ./example1-batch-csv.sh 
22:20:42.935 [main] DEBUG es.upm.fi.dia.oeg.morph.r2rml.rdb.engine.MorphCSVRunner$ - propertiesDirectory = examples-csv
[ . . . ]
22:20:44.232 [main] INFO  es.upm.fi.dia.oeg.morph.r2rml.model.R2RMLMappingDocument$ - Parsing mapping document https://github.com/oeg-upm/morph-rdb/blob/master/morph-examples/examples-csv/example1-mapping-csv.ttl
org.apache.jena.riot.RiotException: [line: 7, col: 11] Bad character in IRI (space): <!DOCTYPE[space]...>
	at org.apache.jena.riot.system.ErrorHandlerFactory$ErrorHandlerStd.fatal(ErrorHandlerFactory.java:136)
	at org.apache.jena.riot.lang.LangEngine.raiseException(LangEngine.java:165)
	[ . . . ]
```

The mapping document retrieved from that URL appears to be an HTML-formatted rendition of the Turtle document, rather than the Turtle document itself:
```
$ wget https://github.com/oeg-upm/morph-rdb/blob/master/morph-examples/examples-csv/example1-mapping-csv.ttl
[ . . . ]
$ head example1-mapping-csv.ttl 
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
```
Jena riot tries to parse it as Turtle, but barfs on '<!DOCTYPE html>' because it contains a space.  If you look at https://github.com/oeg-upm/morph-rdb/blob/master/morph-examples/examples-csv/example1-mapping-csv.ttl in a browser you can see that it is the github-HTML-formatted rendition.

Perhaps the github "raw" version at https://raw.githubusercontent.com/oeg-upm/morph-rdb/master/morph-examples/examples-csv/example1-mapping-csv.ttl needs to be referenced instead of the HTML-formatted version?

**Comment by fpriyatna** [comment]
Hi David, thanks for interest on this project and trying it.

You are right, it should have been the raw URL instead of the HTML one.
For the mapping document, it's either one of these:
- mappingdocument.file.path=example1-mapping-csv.ttl
- mappingdocument.file.path=https://raw.githubusercontent.com/oeg-upm/morph-rdb/master/morph-examples/examples-csv/example1-mapping-csv.ttl

For the csv file path, it's eother one of these:
- csv.file.path = Sport.csv, Student.csv
- csv.file.path = https://raw.githubusercontent.com/oeg-upm/morph-rdb/master/morph-examples/examples-csv/Sport.csv,https://raw.githubusercontent.com/oeg-upm/morph-rdb/master/morph-examples/examples-csv/Student.csv

**Comment by dachafra** [comment]
issue solved
